CREATE TABLE IF NOT EXISTS responses (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  nama TEXT NOT NULL,
  tanggal_lahir TEXT NOT NULL,
  jenis_kelamin TEXT NOT NULL,
  pekerjaan TEXT NOT NULL,
  jabatan TEXT NOT NULL,
  nomor_hp TEXT NOT NULL,
  bersedia INTEGER NOT NULL DEFAULT 1,
  -- Jawaban soal 1-27 (nilai 0-5)
  q1 INTEGER, q2 INTEGER, q3 INTEGER, q4 INTEGER,
  q5 INTEGER, q6 INTEGER, q7 INTEGER, q8 INTEGER,
  q9 INTEGER, q10 INTEGER, q11 INTEGER, q12 INTEGER,
  q13 INTEGER, q14 INTEGER, q15 INTEGER, q16 INTEGER,
  q17 INTEGER, q18 INTEGER, q19 INTEGER, q20 INTEGER,
  q21 INTEGER, q22 INTEGER, q23 INTEGER, q24 INTEGER,
  q25 INTEGER, q26 INTEGER, q27 INTEGER,
  total_score INTEGER,
  kategori TEXT
);
